defaults: &defaults
  aws_key: ''
  aws_secret: ''
  aws_region: 'us-east-1'
  aws_s3_base: "https://s3.amazonaws.com"
  aws_s3_bucket: "littlesis-dev"
  square_image_file_type: jpg
  imagemagick_binary_path: "/usr/bin/convert"
  google_custom_search_engine_id:
  google_custom_news_search_engine_id:
  google_custom_search_key: 
  default_from_email: dev@littlesis.org
  default_to_email: dev@littlesis.org
  admins_only: false
  convert_new_legacy_notes: true
  verticalresponse_username:
  verticalresponse_password:
  research_from_email: research@littlesis.org
  netmap_api_key: freeapiforlittlesisdevs
  netmap_default_width: 960
  netmap_default_height: 550
  twitter_consumer_key:
  twitter_consumer_secret:
  twitter_access_token:
  twitter_access_token_secret:
  twitter_list_id:
  google_site_verification:
  google_analytics_id:
  default_image_file_type: jpg
  system_user_id: 1
  symfony_path: /var/www/littleis/symfony
  bing_maps_key:
  default_network_id: 79
  asset_host: "dfl6orqdcqt4f.cloudfront.net"
  cloudfront_distribtion_id:
  smtp_address: "mail.littlesis.org"
  smtp_port: 465
  smtp_domain: "littlesis.org"
  smtp_user_name: "staff@littlesis.org"
  smtp_password: ""
  smtp_authentication: 'plain'
  notification_email: "email.robot@littlesis.org"
  notification_user_name: "email.robot@littlesis.org"
  notification_password: ""
  notification_to: "test@littlesis.org"
  legacy_cache_connection: "memcached:11211"
  carousel_list_id: 404
  restricted_ips:
    - 192.0.2.1
  chat:
    chat_url: "http://localhost:3000"
    mongo_url: "mongo:27017"
    api_url: "http://rocketchat:3000"
    admin_username: "admin"
    admin_password: "admin"
  recaptcha:
    site_key: 'your-recaptcha-site-key-here'
    secret_key: 'your-recaptcha-secret-key-here'

test:
  <<: *defaults

development:
  <<: *defaults

production:
  <<: *defaults
